# Generated by Django 5.2.4 on 2025-09-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_client_alter_booking_staff'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
